function(GET_SRCS _RT_SRCS SUB_DIRS)
    #message(STATUS "invoke Get_SubSrcs")
    #message(STATUS "${ARGC}")
    #message(STATUS "${${SUB_DIRS}}")

    list(LENGTH ${SUB_DIRS} sub_cnt)
    #message(STATUS "${${sub_cnt}}")
    if(sub_cnt)
    set(SUB_SRCS)
    foreach(SUBDIR ${${SUB_DIRS}})
        get_directory_property(SRCS DIRECTORY ${SUBDIR} DEFINITION ${SUBDIR}_SRCLISTS)
	#MESSAGE(STATUS ${SRCS})
        foreach(SRC ${SRCS})
		list(APPEND SUB_SRCS ${SUBDIR}/${SRC})
        endforeach()
    endforeach()
    endif()
    aux_source_directory(. SUB_SRCS)
    #message(STATUS ${SUB_SRCS})
    set(${_RT_SRCS} ${SUB_SRCS} PARENT_SCOPE)
endfunction()
